#
# AVAILABLE PLACEHOLDERS
#   %player%, %player_displayname%: The message receiver's name/displayname
#   %other%, %other_displayname%: The target's name/displayname
#

message:
  # The message cooldown time for on-damage. in milliseconds. -1 to disable.
  # default = 3000 (3 seconds)
  cooldown-time: 3000
  self:
    on-enable: "&aYour PvP has been Enabled."
    on-disable: "&cYour PvP has been Disabled."
    on-perm-lack: "&cYou do not have permission to execute this command."
    # will be sent when "you" have pvp disabled.
    on-damage: "&cYou cannot damage %other_displayname% while your PvP is Disabled."
  other:
    on-enable: "&aYou have been changed %other_displayname%'s PvP Status to Enabled."
    on-disable: "&cYou have been changed %other_displayname%'s PvP Status to Disabled."
    on-offline: "&cPlayer %other% is not online."
    on-perm-lack: "&cYou cannot change others PvP Status."
    # will be sent when "hitting player" has pvp disabled.
    on-damage: "&cYou cannot damage %other_displayname% while %other_displayname%'s PvP is not Enabled."