# %1$s = Self DisplayName
# %2$s = Another Player DisplayName. available on "message.self.on-damage" or in "message.other"
message:
  self: # Message that will be sent with self behavior.
    on-enable: "&aYour PvP has been Enabled."
    on-disable: "&cYour PvP has been Disabled."
    on-damage: "&cYou cannot damage %2$s while your PvP is Disabled." # will be sent when "self" has pvp disabled.
  other: # Message that will be sent with other player behavior.
    on-enable: "&aYou changed %2$s's PvP Status to Enabled."
    on-disable: "&cYou changed %2$s's PvP Status to Disabled."
    on-offline: "&cPlayer %2$s is not online."
    on-perm-lack: "&cYou do not have permission to execute this command." # ONLY USED FOR OTHER PERMISSION CHECK.
    on-damage: "&cYou cannot damage %2$s while %2$s's PvP is not Enabled." # will be sent when "other" player has pvp disabled.