main: "com.github.derpynewbie.togglepvp.TogglePvP"
name: "PvPToggler"
author: "https://github.com/DerpyNewbie"
description: "Allows players to toggle PvP By them selves."
version: "1.0.0-SNAPSHOT"
api-version: "1.14"
commands:
  TogglePvP:
    description: "Toggles your PvP."
    usage: "/<command> | /<command> [on|off] | /<command> <player> [on|off]"
    permission: "togglepvp.toggle"
    permission-message: "&cYou do not have enough permission to execute this command."
permissions:
  togglepvp.*:
    description: "Allows player to use all feature (only one) in toggle pvp."
    default: "op"
    children:
      togglepvp.toggle: true
  togglepvp.toggle:
    description: "Allows player to use toggle pvp command."
    default: "true"
  togglepvp.toggle.other:
    description: "Allows player to use toggle pvp as changing other's status"
    default: "false"