main: "dev.derpynewbie.mc.togglepvp.TogglePvPPlugin"
name: "DerpyTogglePvP"
author: "DerpyNewbie"
website: "https://github.com/derpynewbie/toggle-pvp-plugin"
description: "Allows players to toggle PvP By them selves."
version: ${project.version}-${buildNumber}
depend: [WorldGuard]
api-version: "1.13"
commands:
  togglepvp:
    description: "Toggles your PvP."
    aliases: [pvp]
    usage: "/<command> | /<command> [on|off] | /<command> <player> [on|off]"
    permission: "togglepvp.toggle"
permissions:
  togglepvp.*:
    description: "Allows player to use all feature (only one) in toggle pvp."
    default: "op"
    children:
      togglepvp.toggle: true
      togglepvp.toggle.other: true
  togglepvp.toggle:
    description: "Allows player to use toggle pvp command."
    default: "true"
  togglepvp.toggle.other:
    description: "Allows player to use toggle pvp as changing other's status"
    default: "op"